[2023-01-06T12:30:31.327+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:30:31.348+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:30:31.349+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:30:31.349+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T12:30:31.349+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:30:31.364+0000] {taskinstance.py:1389} INFO - Executing <Task(EmrTerminateJobFlowOperator): end_emr_cluster> on 2023-01-06 00:00:00+00:00
[2023-01-06T12:30:31.368+0000] {standard_task_runner.py:52} INFO - Started process 100 to run task
[2023-01-06T12:30:31.371+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'end_emr_cluster', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '3823', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmpj0_tee_5', '--error-file', '/tmp/tmpof2l_xji']
[2023-01-06T12:30:31.371+0000] {standard_task_runner.py:80} INFO - Job 3823: Subtask end_emr_cluster
[2023-01-06T12:30:31.385+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:538: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-06T12:30:31.442+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [running]> on host 370ed6868bc3
[2023-01-06T12:30:31.544+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=end_emr_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-06T12:30:31.556+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T12:30:31.556+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T12:30:31.609+0000] {emr.py:410} INFO - Terminating JobFlow None
[2023-01-06T12:30:32.941+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 411, in execute
    response = emr.terminate_job_flows(JobFlowIds=[self.job_flow_id])
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the TerminateJobFlows operation: Specified job flow ID not valid.
[2023-01-06T12:30:32.967+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=atn_import_data_from_apis, task_id=end_emr_cluster, execution_date=20230106T000000, start_date=20230106T123031, end_date=20230106T123032
[2023-01-06T12:30:32.989+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 3823 for task end_emr_cluster (An error occurred (ValidationException) when calling the TerminateJobFlows operation: Specified job flow ID not valid.; 100)
[2023-01-06T12:30:32.998+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-06T12:30:33.039+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-06T13:21:27.399+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T13:21:27.417+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T13:21:27.417+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T13:21:27.417+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T13:21:27.417+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T13:21:27.429+0000] {taskinstance.py:1389} INFO - Executing <Task(EmrTerminateJobFlowOperator): end_emr_cluster> on 2023-01-06 00:00:00+00:00
[2023-01-06T13:21:27.433+0000] {standard_task_runner.py:52} INFO - Started process 288 to run task
[2023-01-06T13:21:27.436+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'end_emr_cluster', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '3894', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmp81t7bfz8', '--error-file', '/tmp/tmpjp1xmaq9']
[2023-01-06T13:21:27.436+0000] {standard_task_runner.py:80} INFO - Job 3894: Subtask end_emr_cluster
[2023-01-06T13:21:27.450+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:538: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-06T13:21:27.500+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.end_emr_cluster scheduled__2023-01-06T00:00:00+00:00 [running]> on host 370ed6868bc3
[2023-01-06T13:21:27.583+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=end_emr_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-06T13:21:27.594+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T13:21:27.594+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T13:21:27.648+0000] {emr.py:410} INFO - Terminating JobFlow j-3J07UP5RPSGPC
[2023-01-06T13:21:31.768+0000] {emr.py:416} INFO - JobFlow with id j-3J07UP5RPSGPC terminated
[2023-01-06T13:21:31.807+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_import_data_from_apis, task_id=end_emr_cluster, execution_date=20230106T000000, start_date=20230106T132127, end_date=20230106T132131
[2023-01-06T13:21:31.854+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T13:21:31.899+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
