[2023-01-06T13:21:50.265+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.upload_put_exchanges_dim_to_s3 manual__2023-01-06T13:21:32.663212+00:00 [queued]>
[2023-01-06T13:21:50.276+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.upload_put_exchanges_dim_to_s3 manual__2023-01-06T13:21:32.663212+00:00 [queued]>
[2023-01-06T13:21:50.276+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T13:21:50.277+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T13:21:50.277+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T13:21:50.290+0000] {taskinstance.py:1389} INFO - Executing <Task(LocalFilesystemToS3Operator): upload_put_exchanges_dim_to_s3> on 2023-01-06 13:21:32.663212+00:00
[2023-01-06T13:21:50.295+0000] {standard_task_runner.py:52} INFO - Started process 309 to run task
[2023-01-06T13:21:50.298+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_update_datalake', 'upload_put_exchanges_dim_to_s3', 'manual__2023-01-06T13:21:32.663212+00:00', '--job-id', '3900', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/datalake_update.py', '--cfg-path', '/tmp/tmpu4a5lu71', '--error-file', '/tmp/tmpv8px8h1o']
[2023-01-06T13:21:50.299+0000] {standard_task_runner.py:80} INFO - Job 3900: Subtask upload_put_exchanges_dim_to_s3
[2023-01-06T13:21:50.365+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_update_datalake.upload_put_exchanges_dim_to_s3 manual__2023-01-06T13:21:32.663212+00:00 [running]> on host 370ed6868bc3
[2023-01-06T13:21:50.438+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_update_datalake
AIRFLOW_CTX_TASK_ID=upload_put_exchanges_dim_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T13:21:32.663212+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T13:21:32.663212+00:00
[2023-01-06T13:21:50.450+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T13:21:50.451+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T13:21:52.080+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_update_datalake, task_id=upload_put_exchanges_dim_to_s3, execution_date=20230106T132132, start_date=20230106T132150, end_date=20230106T132152
[2023-01-06T13:21:52.128+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T13:21:52.208+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
