[2023-01-08T14:21:01.474+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.upload_init_py_to_s3 manual__2023-01-08T14:20:41.774645+00:00 [queued]>
[2023-01-08T14:21:01.490+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.upload_init_py_to_s3 manual__2023-01-08T14:20:41.774645+00:00 [queued]>
[2023-01-08T14:21:01.490+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T14:21:01.490+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-08T14:21:01.491+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-08T14:21:01.507+0000] {taskinstance.py:1389} INFO - Executing <Task(LocalFilesystemToS3Operator): upload_init_py_to_s3> on 2023-01-08 14:20:41.774645+00:00
[2023-01-08T14:21:01.512+0000] {standard_task_runner.py:52} INFO - Started process 74 to run task
[2023-01-08T14:21:01.516+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'upload_init_py_to_s3', 'manual__2023-01-08T14:20:41.774645+00:00', '--job-id', '3967', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmp1p47fe1r', '--error-file', '/tmp/tmp_1m3f2ah']
[2023-01-08T14:21:01.517+0000] {standard_task_runner.py:80} INFO - Job 3967: Subtask upload_init_py_to_s3
[2023-01-08T14:21:01.597+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.upload_init_py_to_s3 manual__2023-01-08T14:20:41.774645+00:00 [running]> on host 370ed6868bc3
[2023-01-08T14:21:01.689+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=upload_init_py_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T14:20:41.774645+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T14:20:41.774645+00:00
[2023-01-08T14:21:01.702+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-08T14:21:01.702+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-08T14:21:02.474+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_import_data_from_apis, task_id=upload_init_py_to_s3, execution_date=20230108T142041, start_date=20230108T142101, end_date=20230108T142102
[2023-01-08T14:21:02.534+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-08T14:21:02.606+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
