[2023-01-06T12:28:15.141+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.create_bucket scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:28:15.185+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.create_bucket scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:28:15.185+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:28:15.186+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T12:28:15.186+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:28:15.210+0000] {taskinstance.py:1389} INFO - Executing <Task(S3CreateBucketOperator): create_bucket> on 2023-01-06 00:00:00+00:00
[2023-01-06T12:28:15.215+0000] {standard_task_runner.py:52} INFO - Started process 62 to run task
[2023-01-06T12:28:15.219+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'create_bucket', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '3812', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmpg7gd71ix', '--error-file', '/tmp/tmp3sqjrq12']
[2023-01-06T12:28:15.220+0000] {standard_task_runner.py:80} INFO - Job 3812: Subtask create_bucket
[2023-01-06T12:28:15.284+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:538: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-06T12:28:15.450+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.create_bucket scheduled__2023-01-06T00:00:00+00:00 [running]> on host 370ed6868bc3
[2023-01-06T12:28:15.643+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=create_bucket
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-06T12:28:15.686+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T12:28:15.689+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T12:28:18.813+0000] {s3.py:75} INFO - Bucket with name: atn-dl-data already exists
[2023-01-06T12:28:18.850+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_import_data_from_apis, task_id=create_bucket, execution_date=20230106T000000, start_date=20230106T122815, end_date=20230106T122818
[2023-01-06T12:28:18.904+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T12:28:18.988+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-06T12:32:54.685+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.create_bucket scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:32:54.696+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.create_bucket scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:32:54.696+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:32:54.696+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T12:32:54.696+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:32:54.711+0000] {taskinstance.py:1389} INFO - Executing <Task(S3CreateBucketOperator): create_bucket> on 2023-01-06 00:00:00+00:00
[2023-01-06T12:32:54.715+0000] {standard_task_runner.py:52} INFO - Started process 104 to run task
[2023-01-06T12:32:54.719+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'create_bucket', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '3825', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmpp0y5u4sa', '--error-file', '/tmp/tmpoa8v34qr']
[2023-01-06T12:32:54.719+0000] {standard_task_runner.py:80} INFO - Job 3825: Subtask create_bucket
[2023-01-06T12:32:54.734+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:538: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-06T12:32:54.787+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.create_bucket scheduled__2023-01-06T00:00:00+00:00 [running]> on host 370ed6868bc3
[2023-01-06T12:32:54.869+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=create_bucket
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-06T12:32:54.882+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T12:32:54.882+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T12:32:55.811+0000] {s3.py:75} INFO - Bucket with name: atn-dl-data already exists
[2023-01-06T12:32:55.834+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_import_data_from_apis, task_id=create_bucket, execution_date=20230106T000000, start_date=20230106T123254, end_date=20230106T123255
[2023-01-06T12:32:55.859+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T12:32:55.938+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
